export const breakpoints = {
  'phone': '(max-width: 320px)',
  '<mobile': '(max-width: 666px)',
  '<=mobile': '(max-width: 667px)',
  '>=mobile': '(min-width: 667px)',
  '>mobile': '(min-width: 668px)',
  '<tablet': '(max-width: 767px)',
  '<=tablet': '(max-width: 768px)',
  '>=tablet': '(min-width: 768px)',
  '>tablet': '(min-width: 769px)',
  '<povertyscreen': '(max-width: 839px)',
  '<=povertyscreen': '(max-width: 840px)',
  '>=povertyscreen': '(min-width: 840px)',
  '>povertyscreen': '(min-width: 841px)',
  '<smallscreen': '(max-width: 959px)',
  '<=smallscreen': '(max-width: 960px)',
  '>=smallscreen': '(min-width: 960px)',
  '>smallscreen': '(min-width: 961px)',
  '<desktop': '(max-width: 1023px)',
  '<=desktop': '(max-width: 1024px)',
  '>=desktop': '(min-width: 1024px)',
  '>desktop': '(min-width: 1025px)',
  '<widescreen': '(max-width: 1139px)',
  '<=widescreen': '(max-width: 1140px)',
  '>=widescreen': '(min-width: 1140px)',
  '>widescreen': '(min-width: 1141px)',

  '<widescreen >=smallscreen': '(max-width: 1139px) and (min-width: 960px)'
};
